<?php

namespace Database\Seeders;

use App\Models\SurCharge;
use Illuminate\Database\Seeder;

class SurChargeSeeder extends Seeder
{
    public function run(): void
    {
        $entries = [
            ['2ND DAY AIR CHG', '2NDAY'],
            ['ACMES CHARGES', 'ACMES'],
            ['ADDITIONAL CHG', 'ADDL'],
            ['address correction', 'ADD.CR'],
            ['AGENCY CHG', 'AGENCY'],
            ['AIR FREIGHT', 'AIRF'],
            ['air india chg', 'AI CHG'],
            ['AIR LINE CHARGES', 'AIR'],
            ['AIRPORT CHARGES', 'AAI'],
            ['Amendment Charges', 'AMA01'],
            ['AMS CHG', 'AMS'],
            ['ARTIFICIAL JEW', 'ARTFIC'],
            ['AUTO CHG', 'AUTO'],
            ['AWB CHARGES', 'AWBC'],
            ['AWB FEES', 'AWBF'],
            ['AYURVEDIC PRODUCT', 'AYUR'],
            ['BETELNUT', 'BET'],
            ['BLINDS CHG', 'BLINDS'],
            ['BODY LOTION', 'BODY'],
            ['BOXES COLLECTION CHARGES', 'COLL'],
            ['BTD CHG', 'BTD'],
            ['CAMPHOR', 'CAMPHO'],
            ['CANDLE', 'CANDLE'],
            ['CART.TRANSPORT CHG', 'C/TPT'],
            ['CELEBI CHGRS', 'CELEBI'],
            ['CGC CHG', 'CGC'],
            ['CHILLY SAUCE', 'CHILLY'],
            ['CHINA CLEARENCE', 'CHI'],
            ['CHOCOLATE CHG', 'CHOC'],
            ['COFFEE', 'COFF'],
            ['COLLECTION CHG', 'COLLEC'],
            ['COMMERCIAL', 'COM'],
            ['COMMERCIAL CHG', 'COMME'],
            ['COSMETIC ITEMS', 'COSME'],
            ['COST RECOVERY', 'COST'],
            ['COVID CHARGES', 'COV'],
            ['CREAME', 'CREAM'],
            ['CSB-IV', 'CSB-IV'],
            ['CSB-V', 'CSB-V'],
            ['CURRENCY EFFECT SURCHARGE', 'CEF'],
            ['CUSTOM HANDLING', 'CUSTH'],
            ['custom messenger fee', 'CMF'],
            ['CUSTOM RE-ENTRY FILLING', 'CUS'],
            ['CUSTOME CLEARING', 'CUST'],
            ['DDP CHG', 'DDP'],
            ['DEL-BLR', 'FRT'],
            ['DEL-BLR FARE', 'DEL-BL'],
            ['DELHI TO CHENNAI FREIGHT', 'DOM'],
            ['DELIVERY CHG', 'DELV'],
            ['DEMAND SURCHARGE', 'DS'],
            ['DENTAL ITEM', 'DENT'],
            ['DISBURSEMENT FEES', 'DISB'],
            ['DO', 'DEO'],
            ['door delivery charges', 'DDC'],
            ['DPD DROP', 'DPD'],
            ['DUTY', 'DUTY'],
            ['DUTY TAX PAID', 'DTP'],
            ['EATABLE ITEMS', 'EAT'],
            ['ECM CORRECTION', 'ECM'],
            ['EICI CHARGES', 'EICI'],
            ['ELECTRIC ITEMS', 'ELEC'],
            ['ELEVATED RISK', 'ELEVAT'],
            ['ex work charges', 'EXW'],
            ['EXPORT CLEARENCE', 'EXPO'],
            ['EXPORT DECLARATION', 'EXP'],
            ['EXPORT DECLARATION CHARGES', 'EDC'],
            ['EXPRESS DELIVERY', 'EXPDL'],
            ['EXTRA FOR MOBILE', 'EMC'],
            ['EXTRA PCS. CHARGES', 'EP'],
            ['Extract', 'EXT'],
            ['FACE WASH', 'FACE'],
            ['facilitation fee', 'FACILI'],
            ['FASHION ACCESSORY WATCH', 'FA WAT'],
            ['FEDEX DROP CH', 'FDX DR'],
            ['FOOD ITEM', 'FOOD'],
            ['FORMAL CLEARENCE CHRGS', 'FOR'],
            ['FORMAL EXPORT DECLARATION', 'FOR01'],
            ['FRDM CHG', 'FRDM'],
            ['FREIGHT CHARGES', 'FRTC'],
            ['FRIDAY DELV.CHG', 'FRI DL'],
            ['FUMIGATION CHG', 'FUMI'],
            ['GEL', 'GEL'],
            ['GHEE', 'GHEE'],
            ['GLUCOMETERS', 'GLUCO'],
            ['GO GREEN PLUS CHG', 'GGP'],
            ['HAIR WAX', 'HAIR'],
            ['HANDLING CHARGES', 'HAN'],
            ['Handling Chgs', 'HAN01'],
            ['HAVAN PRODUCT', 'HAV'],
            ['HERBAL PRODUCT', 'HERB'],
            ['HOUSE D.O CHARGES', 'HOU'],
            ['IAAI CHARGES', 'IAAI'],
            ['import service charge', 'ISC'],
            ['INCENSE STICKS', 'INCE'],
            ['IPF CHARGES', 'IPF'],
            ['JEWELERY APPRAISE', 'APP'],
            ['KITCHEN ITEM', 'KIT'],
            ['LABEL CHARGE', 'LABEL'],
            ['LANCING DEVICE', 'LANCIN'],
            ['LEATHER', 'LEA'],
            ['LEAVES', 'LEAVES'],
            ['LHR BAG HANDLING CHG', 'LHRBAG'],
            ['LOAD HANDLING & CLEARENCE CHG (FRANKFURT)', 'LOAD H'],
            ['LOAD HANDLING & CLEARENCE CHG(FRANKFURT)', 'CLR CH'],
            ['LOADING CHG', 'LOADIN'],
            ['magaj', 'MAGAJ'],
            ['MATERIAL COST', 'MATC'],
            ['MEDICINE CHARGES', 'MED'],
            ['MEHNDI', 'MEH'],
            ['MG BROHTERS', 'MGB08'],
            ['MISC CHARGES', 'MISC'],
            ['MJ CHG', 'MJ CHG'],
            ['MO CHARGES', 'MO CHG'],
            ['MOUTH FRESHNER', 'MOUTH'],
            ['MUKHWASH', 'MUKH'],
            ['NEXT DAY CHARGES', 'ND'],
            ['NJ TO NY TRANSPORTATION', 'NJ'],
            ['NON CONVEYABLE PCS', 'NON'],
            ['ODA CHG', 'ODA'],
            ['OFLOADING CHG', 'OFLOAD'],
            ['OIL', 'OIL'],
            ['ONE TOUCH DELICA', 'ONETO'],
            ['OSC CHARGES', 'OSC'],
            ['OTHER CHARGES', 'OTH'],
            ['OVERSIZE', 'OVS'],
            ['OVERWEIGHT CHARGES', 'OVW'],
            ['PACKING CHRG', 'PKC'],
            ['PALLET', 'PALLET'],
            ['PASPORT', 'PP'],
            ['PCA CHARGES', 'PCA'],
            ['PENALTY', 'PEN'],
            ['PER KG CHARGES', 'PER KG'],
            ['PERFUME CHG', 'PERF'],
            ['PICKUP COST', 'PICK'],
            ['PIMS PENALTY', 'PIMS'],
            ['PKUP CHARGES', 'PKUP'],
            ['PORTAR CHG', 'PORTAR'],
            ['POWDER', 'POWD'],
            ['RAJ INTL', 'RAJ56'],
            ['RE-SHIP CHG', 'RESHIP'],
            ['REMOTE AREA', 'RA'],
            ['REMOTE PICKUP COST', 'REM01'],
            ['RESTRICTED AREA', 'RES AR'],
            ['RICE CHG', 'RICE'],
            ['ROSE WATER', 'ROSE'],
            ['RTO CHARGES', 'RTO'],
            ['SARA CREATION', 'SARAC'],
            ['SATURDAY DLV. CHARGES', 'SAT'],
            ['SEEDS', 'SEEDS'],
            ['SERVICE CHARGE', 'SER'],
            ['SHAMPOO', 'SHAM'],
            ['SHIPPING BILL CHG', 'SHIPB'],
            ['SIGNATURE REQUIRED', 'SIG RQ'],
            ['SINGLE PCS CHG', 'SINGLE'],
            ['SOAP', 'SOAP'],
            ['special handling charge (AUG TO OCT) LAX@28/-PKG', 'SPL CH'],
            ['SPICES', 'SPICE'],
            ['SPRAY', 'SPRAY'],
            ['SUNDAY DLV. CHARGES', 'SUN'],
            ['SUPPLEMENT CHG', 'SUPL'],
            ['SURGE FEE', 'SURG'],
            ['SVM INC', 'SVMINC'],
            ['SWEETS', 'SWEETS'],
            ['TEA', 'TEA'],
            ['TEMPO CHG', 'TEMPO'],
            ['TEMPORARY ADDITIONAL SURCHARGE', 'TAS'],
            ['TOBACCO', 'TOBAC'],
            ['TOOTHPASTE', 'TOOTH'],
            ['USPS DROP CHG', 'USPS'],
            ['VAT', 'VAT'],
            ['volume diff amt.', 'VOLDIF'],
            ['WAREHOUSE CHARGES', 'WARE'],
            ['WATCH CHG', 'WATCH'],
            ['WITHDRWAL CHG', 'WITHDR'],
            ['WOODEN CHG', 'WOODEN'],
            ['x-ray chg', 'X RAY'],
        ];

        foreach ($entries as $entry) {
            SurCharge::updateOrCreate(
                ['code' => $entry[1]],
                ['name' => $entry[0], 'price' => 0]
            );
        }
    }
}