<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Seeds the `zone` table with sample UK postcodes and Canada postal codes
 * so that the create-shipment page can show zipcode suggestions for those
 * destinations.
 *
 * - UK  → destination_id = 2, zone_category = 'zipcode'
 * - CA  → destination_id = 3, zone_category = 'zipcode'
 *
 * The `zone_category` column is expected to already exist on the `zone`
 * table (added manually). This migration only guards against its absence
 * and inserts the sample rows.
 */
return new class extends Migration
{
    public function up(): void
    {
        // Guard: if zone_category column does not exist, add it (defensive).
        if (!Schema::hasColumn('zone', 'zone_category')) {
            Schema::table('zone', function ($table) {
                $table->string('zone_category', 20)->nullable()->default('state')->after('zone_code');
            });
        }

        // Ensure existing US state rows are tagged as 'state'.
        DB::table('zone')
            ->whereNull('zone_category')
            ->update(['zone_category' => 'state']);

        $now = now()->format('Y-m-d H:i:s');

        $ukDestination = DB::table('destinations')->where('code', 'UK')->first();
        $caDestination = DB::table('destinations')->where('code', 'CA')->first();

        // ---- Sample UK postcodes (outward codes) ----
        $ukZones = [
            ['AB10', 'Aberdeen'],
            ['AB11', 'Aberdeen'],
            ['AB12', 'Aberdeen'],
            ['B1',   'Birmingham'],
            ['B2',   'Birmingham'],
            ['B3',   'Birmingham'],
            ['CF10', 'Cardiff'],
            ['CF11', 'Cardiff'],
            ['CF23', 'Cardiff'],
            ['CV1',  'Coventry'],
            ['CV2',  'Coventry'],
            ['CV3',  'Coventry'],
            ['EH1',  'Edinburgh'],
            ['EH2',  'Edinburgh'],
            ['EH3',  'Edinburgh'],
            ['G1',   'Glasgow'],
            ['G2',   'Glasgow'],
            ['G3',   'Glasgow'],
            ['L1',   'Liverpool'],
            ['L2',   'Liverpool'],
            ['L3',   'Liverpool'],
            ['LE1',  'Leicester'],
            ['LE2',  'Leicester'],
            ['LE3',  'Leicester'],
            ['M1',   'Manchester'],
            ['M2',   'Manchester'],
            ['M3',   'Manchester'],
            ['M4',   'Manchester'],
            ['NE1',  'Newcastle upon Tyne'],
            ['NE2',  'Newcastle upon Tyne'],
            ['NE3',  'Newcastle upon Tyne'],
            ['LS1',  'Leeds'],
            ['LS2',  'Leeds'],
            ['LS3',  'Leeds'],
            ['NG1',  'Nottingham'],
            ['NG2',  'Nottingham'],
            ['NG7',  'Nottingham'],
            ['OL1',  'Oldham'],
            ['OL2',  'Oldham'],
            ['OL3',  'Oldham'],
            ['PR1',  'Preston'],
            ['PR2',  'Preston'],
            ['PR3',  'Preston'],
            ['S1',   'Sheffield'],
            ['S2',   'Sheffield'],
            ['S3',   'Sheffield'],
            ['SW1',  'London'],
            ['SW2',  'London'],
            ['SW3',  'London'],
            ['SW4',  'London'],
            ['SW5',  'London'],
            ['SW6',  'London'],
            ['SW7',  'London'],
            ['SW8',  'London'],
            ['SW9',  'London'],
            ['SW10', 'London'],
            ['W1',   'London'],
            ['W2',   'London'],
            ['W3',   'London'],
            ['W4',   'London'],
            ['W5',   'London'],
            ['W6',   'London'],
            ['W7',   'London'],
            ['W8',   'London'],
            ['W9',   'London'],
            ['W10',  'London'],
            ['W11',  'London'],
            ['E1',   'London'],
            ['E2',   'London'],
            ['E3',   'London'],
            ['E4',   'London'],
            ['E5',   'London'],
            ['E6',   'London'],
            ['E7',   'London'],
            ['E8',   'London'],
            ['E9',   'London'],
            ['E10',  'London'],
            ['E11',  'London'],
            ['N1',   'London'],
            ['N2',   'London'],
            ['N3',   'London'],
            ['N4',   'London'],
            ['N5',   'London'],
            ['N6',   'London'],
            ['N7',   'London'],
            ['N8',   'London'],
            ['N9',   'London'],
            ['N10',  'London'],
            ['N11',  'London'],
            ['CR0',  'Croydon'],
            ['CR2',  'Croydon'],
            ['CR4',  'Croydon'],
            ['BR1',  'Bromley'],
            ['BR2',  'Bromley'],
            ['BR3',  'Bromley'],
            ['TW1',  'Twickenham'],
            ['TW2',  'Twickenham'],
            ['KT1',  'Kingston upon Thames'],
            ['KT2',  'Kingston upon Thames'],
            ['KT3',  'Kingston upon Thames'],
            ['UB1',  'Southall'],
            ['UB2',  'Southall'],
            ['IG1',  'Ilford'],
            ['IG2',  'Ilford'],
            ['RM1',  'Romford'],
            ['RM2',  'Romford'],
            ['DA1',  'Dartford'],
            ['DA2',  'Dartford'],
            ['SL1',  'Slough'],
            ['SL2',  'Slough'],
            ['HP1',  'Hemel Hempstead'],
            ['HP2',  'Hemel Hempstead'],
            ['MK1',  'Milton Keynes'],
            ['MK2',  'Milton Keynes'],
            ['MK3',  'Milton Keynes'],
            ['OX1',  'Oxford'],
            ['OX2',  'Oxford'],
            ['CB1',  'Cambridge'],
            ['CB2',  'Cambridge'],
            ['IP1',  'Ipswich'],
            ['IP2',  'Ipswich'],
            ['NR1',  'Norwich'],
            ['NR2',  'Norwich'],
            ['CO1',  'Colchester'],
            ['CO2',  'Colchester'],
            ['SS1',  'Southend-on-Sea'],
            ['SS2',  'Southend-on-Sea'],
            ['CM1',  'Chelmsford'],
            ['CM2',  'Chelmsford'],
            ['AL1',  'St Albans'],
            ['AL2',  'St Albans'],
            ['LU1',  'Luton'],
            ['LU2',  'Luton'],
            ['BN1',  'Brighton'],
            ['BN2',  'Brighton'],
            ['TN1',  'Tunbridge Wells'],
            ['TN2',  'Tunbridge Wells'],
            ['CT1',  'Canterbury'],
            ['CT2',  'Canterbury'],
            ['ME1',  'Rochester'],
            ['ME2',  'Rochester'],
            ['BH1',  'Bournemouth'],
            ['BH2',  'Bournemouth'],
            ['SO1',  'Southampton'],
            ['SO2',  'Southampton'],
            ['PO1',  'Portsmouth'],
            ['PO2',  'Portsmouth'],
            ['EX1',  'Exeter'],
            ['EX2',  'Exeter'],
            ['PL1',  'Plymouth'],
            ['PL2',  'Plymouth'],
            ['TR1',  'Truro'],
            ['TR2',  'Truro'],
            ['BA1',  'Bath'],
            ['BA2',  'Bath'],
            ['BS1',  'Bristol'],
            ['BS2',  'Bristol'],
            ['BS3',  'Bristol'],
            ['GL1',  'Gloucester'],
            ['GL2',  'Gloucester'],
            ['SN1',  'Swindon'],
            ['SN2',  'Swindon'],
            ['DT1',  'Dorchester'],
            ['DT2',  'Dorchester'],
            ['TA1',  'Taunton'],
            ['TA2',  'Taunton'],
            ['EX3',  'Exeter'],
            ['FY1',  'Blackpool'],
            ['FY2',  'Blackpool'],
            ['PR8',  'Southport'],
            ['PR9',  'Southport'],
            ['BB1',  'Blackburn'],
            ['BB2',  'Blackburn'],
            ['BL1',  'Bolton'],
            ['BL2',  'Bolton'],
            ['WN1',  'Wigan'],
            ['WN2',  'Wigan'],
            ['WA1',  'Warrington'],
            ['WA2',  'Warrington'],
            ['CH1',  'Chester'],
            ['CH2',  'Chester'],
            ['CW1',  'Crewe'],
            ['CW2',  'Crewe'],
            ['ST1',  'Stoke-on-Trent'],
            ['ST2',  'Stoke-on-Trent'],
            ['TF1',  'Telford'],
            ['TF2',  'Telford'],
            ['DY1',  'Dudley'],
            ['DY2',  'Dudley'],
            ['WV1',  'Wolverhampton'],
            ['WV2',  'Wolverhampton'],
            ['B5',   'Birmingham'],
            ['B6',   'Birmingham'],
            ['B7',   'Birmingham'],
            ['BD1',  'Bradford'],
            ['BD2',  'Bradford'],
            ['HD1',  'Huddersfield'],
            ['HD2',  'Huddersfield'],
            ['HX1',  'Halifax'],
            ['HX2',  'Halifax'],
            ['WF1',  'Wakefield'],
            ['WF2',  'Wakefield'],
            ['DE1',  'Derby'],
            ['DE2',  'Derby'],
            ['NG9',  'Nottingham'],
            ['NG10', 'Nottingham'],
            ['LE4',  'Leicester'],
            ['LE5',  'Leicester'],
            ['NN1',  'Northampton'],
            ['NN2',  'Northampton'],
            ['MK4',  'Milton Keynes'],
            ['MK5',  'Milton Keynes'],
            ['LU3',  'Luton'],
            ['LU4',  'Luton'],
            ['SG1',  'Stevenage'],
            ['SG2',  'Stevenage'],
            ['HU1',  'Hull'],
            ['HU2',  'Hull'],
            ['DN1',  'Doncaster'],
            ['DN2',  'Doncaster'],
            ['S4',   'Sheffield'],
            ['S5',   'Sheffield'],
            ['S6',   'Sheffield'],
            ['S64',  'Rotherham'],
            ['S65',  'Rotherham'],
            ['S66',  'Rotherham'],
            ['CW3',  'Crewe'],
            ['CW4',  'Crewe'],
            ['FK1',  'Falkirk'],
            ['FK2',  'Falkirk'],
            ['DD1',  'Dundee'],
            ['DD2',  'Dundee'],
            ['AB15', 'Aberdeen'],
            ['AB16', 'Aberdeen'],
            ['IV1',  'Inverness'],
            ['IV2',  'Inverness'],
            ['PH1',  'Perth'],
            ['PH2',  'Perth'],
            ['BT1',  'Belfast'],
            ['BT2',  'Belfast'],
            ['BT3',  'Belfast'],
            ['BT4',  'Belfast'],
            ['BT5',  'Belfast'],
            ['BT6',  'Belfast'],
            ['BT7',  'Belfast'],
            ['BT8',  'Belfast'],
            ['BT9',  'Belfast'],
            ['BT10', 'Belfast'],
            ['BT11', 'Belfast'],
            ['BT12', 'Belfast'],
            ['BT13', 'Belfast'],
            ['BT14', 'Belfast'],
            ['BT15', 'Belfast'],
            ['BT16', 'Belfast'],
            ['BT17', 'Belfast'],
            ['BT18', 'Holywood'],
            ['BT19', 'Bangor'],
            ['BT20', 'Bangor'],
            ['BT21', 'Donaghadee'],
            ['BT22', 'Newtownards'],
            ['BT23', 'Newtownards'],
            ['BT24', 'Ballynahinch'],
            ['BT25', 'Dromore'],
            ['BT26', 'Lisburn'],
            ['BT27', 'Lisburn'],
            ['BT28', 'Lisburn'],
            ['BT29', 'Crumlin'],
            ['BT30', 'Downpatrick'],
            ['BT31', 'Castlewellan'],
            ['BT32', 'Banbridge'],
            ['BT33', 'Newcastle'],
            ['BT34', 'Newry'],
            ['BT35', 'Newry'],
            ['BT36', 'Newtownabbey'],
            ['BT37', 'Newtownabbey'],
            ['BT38', 'Carrickfergus'],
            ['BT39', 'Ballyclare'],
            ['BT40', 'Larne'],
            ['BT41', 'Antrim'],
            ['BT42', 'Ballymena'],
            ['BT43', 'Ballymena'],
            ['BT44', 'Ballymena'],
            ['BT45', 'Magherafelt'],
            ['BT46', 'Magherafelt'],
            ['BT47', 'Derry'],
            ['BT48', 'Derry'],
            ['BT49', 'Limavady'],
            ['BT51', 'Coleraine'],
            ['BT52', 'Coleraine'],
            ['BT53', 'Coleraine'],
            ['BT54', 'Ballycastle'],
            ['BT55', 'Portrush'],
            ['BT56', 'Portrush'],
            ['BT74', 'Enniskillen'],
            ['BT75', 'Enniskillen'],
            ['BT76', 'Enniskillen'],
            ['BT77', 'Omagh'],
            ['BT78', 'Omagh'],
            ['BT79', 'Omagh'],
            ['BT80', 'Cookstown'],
            ['BT81', 'Strabane'],
            ['BT82', 'Strabane'],
            ['BT92', 'Enniskillen'],
            ['BT93', 'Enniskillen'],
            ['BT94', 'Enniskillen'],
        ];

        // ---- Sample Canada postal codes (forward sortation area, e.g. M5H) ----
        $caZones = [
            ['M5H', 'Toronto'],
            ['M5J', 'Toronto'],
            ['M5K', 'Toronto'],
            ['M5L', 'Toronto'],
            ['M5S', 'Toronto'],
            ['M5T', 'Toronto'],
            ['M5V', 'Toronto'],
            ['M5W', 'Toronto'],
            ['M5X', 'Toronto'],
            ['M6G', 'Toronto'],
            ['M6H', 'Toronto'],
            ['M6J', 'Toronto'],
            ['M6K', 'Toronto'],
            ['M6P', 'Toronto'],
            ['M6R', 'Toronto'],
            ['M6S', 'Toronto'],
            ['M4W', 'Toronto'],
            ['M4X', 'Toronto'],
            ['M4Y', 'Toronto'],
            ['M4A', 'Toronto'],
            ['M4B', 'Toronto'],
            ['M4C', 'Toronto'],
            ['M4E', 'Toronto'],
            ['M4G', 'Toronto'],
            ['M4H', 'Toronto'],
            ['M4J', 'Toronto'],
            ['M4K', 'Toronto'],
            ['M4L', 'Toronto'],
            ['M4M', 'Toronto'],
            ['M4N', 'Toronto'],
            ['M4P', 'Toronto'],
            ['M4R', 'Toronto'],
            ['M4S', 'Toronto'],
            ['M4T', 'Toronto'],
            ['M4V', 'Toronto'],
            ['M9A', 'Toronto'],
            ['M9B', 'Toronto'],
            ['M9C', 'Toronto'],
            ['M9R', 'Toronto'],
            ['M9V', 'Toronto'],
            ['M9W', 'Toronto'],
            ['L4W', 'Mississauga'],
            ['L4X', 'Mississauga'],
            ['L4Y', 'Mississauga'],
            ['L4Z', 'Mississauga'],
            ['L5A', 'Mississauga'],
            ['L5B', 'Mississauga'],
            ['L5C', 'Mississauga'],
            ['L5J', 'Mississauga'],
            ['L5K', 'Mississauga'],
            ['L5L', 'Mississauga'],
            ['L5M', 'Mississauga'],
            ['L5N', 'Mississauga'],
            ['L5P', 'Mississauga'],
            ['L5R', 'Mississauga'],
            ['L5S', 'Mississauga'],
            ['L5T', 'Mississauga'],
            ['L5V', 'Mississauga'],
            ['L5W', 'Mississauga'],
            ['L6H', 'Oakville'],
            ['L6J', 'Oakville'],
            ['L6K', 'Oakville'],
            ['L6L', 'Oakville'],
            ['L6M', 'Oakville'],
            ['L6R', 'Brampton'],
            ['L6S', 'Brampton'],
            ['L6T', 'Brampton'],
            ['L6V', 'Brampton'],
            ['L6W', 'Brampton'],
            ['L6X', 'Brampton'],
            ['L6Y', 'Brampton'],
            ['L6Z', 'Brampton'],
            ['L7A', 'Brampton'],
            ['L7B', 'Brampton'],
            ['L7C', 'Brampton'],
            ['L3R', 'Markham'],
            ['L3S', 'Markham'],
            ['L3T', 'Markham'],
            ['L3X', 'Markham'],
            ['L3Y', 'Markham'],
            ['L4A', 'Markham'],
            ['L4B', 'Richmond Hill'],
            ['L4C', 'Richmond Hill'],
            ['L4E', 'Richmond Hill'],
            ['L4S', 'Richmond Hill'],
            ['L5B', 'Mississauga'],
            ['H2X', 'Montreal'],
            ['H2Y', 'Montreal'],
            ['H2Z', 'Montreal'],
            ['H2W', 'Montreal'],
            ['H2T', 'Montreal'],
            ['H2S', 'Montreal'],
            ['H2V', 'Montreal'],
            ['H2R', 'Montreal'],
            ['H2P', 'Montreal'],
            ['H2N', 'Montreal'],
            ['H2M', 'Montreal'],
            ['H2L', 'Montreal'],
            ['H2K', 'Montreal'],
            ['H2J', 'Montreal'],
            ['H2H', 'Montreal'],
            ['H2G', 'Montreal'],
            ['H2E', 'Montreal'],
            ['H2C', 'Montreal'],
            ['H2A', 'Montreal'],
            ['H3A', 'Montreal'],
            ['H3B', 'Montreal'],
            ['H3C', 'Montreal'],
            ['H3E', 'Montreal'],
            ['H3G', 'Montreal'],
            ['H3H', 'Montreal'],
            ['H3J', 'Montreal'],
            ['H3K', 'Montreal'],
            ['H3L', 'Montreal'],
            ['H3M', 'Montreal'],
            ['H3N', 'Montreal'],
            ['H3P', 'Montreal'],
            ['H3R', 'Montreal'],
            ['H3S', 'Montreal'],
            ['H3T', 'Montreal'],
            ['H3V', 'Montreal'],
            ['H3W', 'Montreal'],
            ['H3X', 'Montreal'],
            ['H3Y', 'Montreal'],
            ['H3Z', 'Montreal'],
            ['H4A', 'Montreal'],
            ['H4B', 'Montreal'],
            ['H4C', 'Montreal'],
            ['H4E', 'Montreal'],
            ['H4G', 'Montreal'],
            ['H4H', 'Montreal'],
            ['H4J', 'Montreal'],
            ['H4K', 'Montreal'],
            ['H4L', 'Montreal'],
            ['H4M', 'Montreal'],
            ['H4N', 'Montreal'],
            ['H4P', 'Montreal'],
            ['H4R', 'Montreal'],
            ['H4S', 'Montreal'],
            ['H4T', 'Montreal'],
            ['H4V', 'Montreal'],
            ['H4W', 'Montreal'],
            ['H4X', 'Montreal'],
            ['T5A', 'Edmonton'],
            ['T5B', 'Edmonton'],
            ['T5C', 'Edmonton'],
            ['T5E', 'Edmonton'],
            ['T5G', 'Edmonton'],
            ['T5H', 'Edmonton'],
            ['T5J', 'Edmonton'],
            ['T5K', 'Edmonton'],
            ['T5L', 'Edmonton'],
            ['T5M', 'Edmonton'],
            ['T5N', 'Edmonton'],
            ['T5P', 'Edmonton'],
            ['T5R', 'Edmonton'],
            ['T5S', 'Edmonton'],
            ['T5T', 'Edmonton'],
            ['T5V', 'Edmonton'],
            ['T5W', 'Edmonton'],
            ['T5X', 'Edmonton'],
            ['T5Y', 'Edmonton'],
            ['T5Z', 'Edmonton'],
            ['T6A', 'Edmonton'],
            ['T6B', 'Edmonton'],
            ['T6C', 'Edmonton'],
            ['T6E', 'Edmonton'],
            ['T6G', 'Edmonton'],
            ['T6H', 'Edmonton'],
            ['T6J', 'Edmonton'],
            ['T6K', 'Edmonton'],
            ['T6L', 'Edmonton'],
            ['T6M', 'Edmonton'],
            ['T6N', 'Edmonton'],
            ['T6P', 'Edmonton'],
            ['T6R', 'Edmonton'],
            ['T6S', 'Edmonton'],
            ['T6T', 'Edmonton'],
            ['T6V', 'Edmonton'],
            ['T6W', 'Edmonton'],
            ['T6X', 'Edmonton'],
            ['T2A', 'Calgary'],
            ['T2B', 'Calgary'],
            ['T2C', 'Calgary'],
            ['T2E', 'Calgary'],
            ['T2G', 'Calgary'],
            ['T2H', 'Calgary'],
            ['T2J', 'Calgary'],
            ['T2K', 'Calgary'],
            ['T2L', 'Calgary'],
            ['T2M', 'Calgary'],
            ['T2N', 'Calgary'],
            ['T2P', 'Calgary'],
            ['T2R', 'Calgary'],
            ['T2S', 'Calgary'],
            ['T2T', 'Calgary'],
            ['T2V', 'Calgary'],
            ['T2W', 'Calgary'],
            ['T2X', 'Calgary'],
            ['T2Y', 'Calgary'],
            ['T2Z', 'Calgary'],
            ['T3A', 'Calgary'],
            ['T3B', 'Calgary'],
            ['T3C', 'Calgary'],
            ['T3E', 'Calgary'],
            ['T3G', 'Calgary'],
            ['T3H', 'Calgary'],
            ['T3J', 'Calgary'],
            ['T3K', 'Calgary'],
            ['T3L', 'Calgary'],
            ['T3M', 'Calgary'],
            ['T3N', 'Calgary'],
            ['T3P', 'Calgary'],
            ['T3R', 'Calgary'],
            ['T3S', 'Calgary'],
            ['T3T', 'Calgary'],
            ['T3V', 'Calgary'],
            ['T3W', 'Calgary'],
            ['T3X', 'Calgary'],
            ['V5K', 'Vancouver'],
            ['V5L', 'Vancouver'],
            ['V5M', 'Vancouver'],
            ['V5N', 'Vancouver'],
            ['V5P', 'Vancouver'],
            ['V5R', 'Vancouver'],
            ['V5S', 'Vancouver'],
            ['V5T', 'Vancouver'],
            ['V5V', 'Vancouver'],
            ['V5W', 'Vancouver'],
            ['V5X', 'Vancouver'],
            ['V5Y', 'Vancouver'],
            ['V5Z', 'Vancouver'],
            ['V6A', 'Vancouver'],
            ['V6B', 'Vancouver'],
            ['V6C', 'Vancouver'],
            ['V6E', 'Vancouver'],
            ['V6G', 'Vancouver'],
            ['V6H', 'Vancouver'],
            ['V6J', 'Vancouver'],
            ['V6K', 'Vancouver'],
            ['V6L', 'Vancouver'],
            ['V6M', 'Vancouver'],
            ['V6N', 'Vancouver'],
            ['V6P', 'Vancouver'],
            ['V6R', 'Vancouver'],
            ['V6S', 'Vancouver'],
            ['V6T', 'Vancouver'],
            ['V6V', 'Vancouver'],
            ['V6W', 'Vancouver'],
            ['V6X', 'Vancouver'],
            ['V6Z', 'Vancouver'],
            ['V7X', 'Vancouver'],
            ['V7Y', 'Vancouver'],
            ['R2C', 'Winnipeg'],
            ['R2G', 'Winnipeg'],
            ['R2H', 'Winnipeg'],
            ['R2J', 'Winnipeg'],
            ['R2K', 'Winnipeg'],
            ['R2L', 'Winnipeg'],
            ['R2M', 'Winnipeg'],
            ['R2N', 'Winnipeg'],
            ['R2P', 'Winnipeg'],
            ['R2R', 'Winnipeg'],
            ['R2V', 'Winnipeg'],
            ['R2W', 'Winnipeg'],
            ['R2X', 'Winnipeg'],
            ['R2Y', 'Winnipeg'],
            ['R3A', 'Winnipeg'],
            ['R3B', 'Winnipeg'],
            ['R3C', 'Winnipeg'],
            ['R3E', 'Winnipeg'],
            ['R3G', 'Winnipeg'],
            ['R3H', 'Winnipeg'],
            ['R3J', 'Winnipeg'],
            ['R3K', 'Winnipeg'],
            ['R3L', 'Winnipeg'],
            ['R3M', 'Winnipeg'],
            ['R3N', 'Winnipeg'],
            ['R3P', 'Winnipeg'],
            ['R3R', 'Winnipeg'],
            ['R3S', 'Winnipeg'],
            ['R3T', 'Winnipeg'],
            ['R3V', 'Winnipeg'],
            ['R3W', 'Winnipeg'],
            ['R3X', 'Winnipeg'],
            ['R3Y', 'Winnipeg'],
            ['K1A', 'Ottawa'],
            ['K1B', 'Ottawa'],
            ['K1C', 'Ottawa'],
            ['K1E', 'Ottawa'],
            ['K1G', 'Ottawa'],
            ['K1H', 'Ottawa'],
            ['K1J', 'Ottawa'],
            ['K1K', 'Ottawa'],
            ['K1L', 'Ottawa'],
            ['K1M', 'Ottawa'],
            ['K1N', 'Ottawa'],
            ['K1P', 'Ottawa'],
            ['K1R', 'Ottawa'],
            ['K1S', 'Ottawa'],
            ['K1T', 'Ottawa'],
            ['K1V', 'Ottawa'],
            ['K1W', 'Ottawa'],
            ['K1X', 'Ottawa'],
            ['K1Y', 'Ottawa'],
            ['K1Z', 'Ottawa'],
            ['K2A', 'Ottawa'],
            ['K2B', 'Ottawa'],
            ['K2C', 'Ottawa'],
            ['K2E', 'Ottawa'],
            ['K2G', 'Ottawa'],
            ['K2H', 'Ottawa'],
            ['K2J', 'Ottawa'],
            ['K2K', 'Ottawa'],
            ['K2L', 'Ottawa'],
            ['K2M', 'Ottawa'],
            ['K2P', 'Ottawa'],
            ['K2R', 'Ottawa'],
            ['K2S', 'Ottawa'],
            ['K2T', 'Ottawa'],
            ['K2V', 'Ottawa'],
            ['K2W', 'Ottawa'],
            ['E3B', 'Fredericton'],
            ['E3A', 'Fredericton'],
            ['E3C', 'Fredericton'],
            ['E3E', 'Fredericton'],
            ['B3A', 'Halifax'],
            ['B3B', 'Halifax'],
            ['B3C', 'Halifax'],
            ['B3E', 'Halifax'],
            ['B3G', 'Halifax'],
            ['B3H', 'Halifax'],
            ['B3J', 'Halifax'],
            ['B3K', 'Halifax'],
            ['B3L', 'Halifax'],
            ['B3M', 'Halifax'],
            ['B3N', 'Halifax'],
            ['B3P', 'Halifax'],
            ['B3R', 'Halifax'],
            ['B3S', 'Halifax'],
            ['B3T', 'Halifax'],
            ['B3V', 'Halifax'],
            ['B3Z', 'Halifax'],
            ['C1A', 'Charlottetown'],
            ['C1B', 'Charlottetown'],
            ['C1C', 'Charlottetown'],
            ['C1E', 'Charlottetown'],
            ['A1A', "St. John's"],
            ['A1B', "St. John's"],
            ['A1C', "St. John's"],
            ['A1E', "St. John's"],
            ['A1G', "St. John's"],
            ['A1H', "St. John's"],
            ['A1K', "St. John's"],
            ['A1L', "St. John's"],
            ['A1N', "St. John's"],
            ['A1P', "St. John's"],
            ['A1R', "St. John's"],
            ['A1S', "St. John's"],
            ['A1V', "St. John's"],
            ['A1W', "St. John's"],
            ['A1X', "St. John's"],
            ['A1Y', "St. John's"],
            ['S4P', 'Regina'],
            ['S4R', 'Regina'],
            ['S4S', 'Regina'],
            ['S4T', 'Regina'],
            ['S4V', 'Regina'],
            ['S4W', 'Regina'],
            ['S4X', 'Regina'],
            ['S4Y', 'Regina'],
            ['S2N', 'Saskatoon'],
            ['S2P', 'Saskatoon'],
            ['S2R', 'Saskatoon'],
            ['S2S', 'Saskatoon'],
            ['S2T', 'Saskatoon'],
            ['S2V', 'Saskatoon'],
            ['S3H', 'Saskatoon'],
            ['S3K', 'Saskatoon'],
            ['S3L', 'Saskatoon'],
            ['S3M', 'Saskatoon'],
            ['S3N', 'Saskatoon'],
            ['S3P', 'Saskatoon'],
            ['S3R', 'Saskatoon'],
            ['S4N', 'Saskatoon'],
            ['S4J', 'Saskatoon'],
            ['S4K', 'Saskatoon'],
            ['S4L', 'Saskatoon'],
            ['S4M', 'Saskatoon'],
            ['S4H', 'Saskatoon'],
            ['V8A', 'Victoria'],
            ['V8B', 'Victoria'],
            ['V8C', 'Victoria'],
            ['V8K', 'Victoria'],
            ['V8L', 'Victoria'],
            ['V8M', 'Victoria'],
            ['V8N', 'Victoria'],
            ['V8P', 'Victoria'],
            ['V8R', 'Victoria'],
            ['V8S', 'Victoria'],
            ['V8T', 'Victoria'],
            ['V8V', 'Victoria'],
            ['V8W', 'Victoria'],
            ['V8X', 'Victoria'],
            ['V8Y', 'Victoria'],
            ['V8Z', 'Victoria'],
            ['V9A', 'Victoria'],
            ['V9B', 'Victoria'],
            ['V9C', 'Victoria'],
            ['V9E', 'Victoria'],
            ['V9G', 'Victoria'],
            ['V9J', 'Victoria'],
            ['V9K', 'Victoria'],
            ['V9L', 'Victoria'],
            ['V9M', 'Victoria'],
            ['V9N', 'Victoria'],
            ['V9P', 'Victoria'],
            ['V9R', 'Victoria'],
            ['V9S', 'Victoria'],
            ['V9T', 'Victoria'],
            ['V9V', 'Victoria'],
            ['V9W', 'Victoria'],
            ['V9X', 'Victoria'],
            ['V9Y', 'Victoria'],
            ['V9Z', 'Victoria'],
            ['Y1A', 'Whitehorse'],
            ['X0A', 'Iqaluit'],
            ['X1A', 'Yellowknife'],
        ];

        // Insert UK zones (deduplicated by zone_code per destination).
        if ($ukDestination) {
            foreach ($ukZones as $z) {
                DB::table('zone')->updateOrInsert(
                    [
                        'destination_id' => $ukDestination->id,
                        'zone_code'      => $z[0],
                    ],
                    [
                        'zone_name'         => $z[1],
                        'zone_category'     => 'zipcode',
                        'zone_number'        => 0,
                        'zone_number_testing'=> 0,
                        'created_at'        => $now,
                        'updated_at'        => $now,
                    ]
                );
            }
        }

        // Insert Canada zones (deduplicated by zone_code per destination).
        if ($caDestination) {
            foreach ($caZones as $z) {
                DB::table('zone')->updateOrInsert(
                    [
                        'destination_id' => $caDestination->id,
                        'zone_code'      => $z[0],
                    ],
                    [
                        'zone_name'         => $z[1],
                        'zone_category'     => 'zipcode',
                        'zone_number'        => 0,
                        'zone_number_testing'=> 0,
                        'created_at'        => $now,
                        'updated_at'        => $now,
                    ]
                );
            }
        }
    }

    public function down(): void
    {
        $ukDestination = DB::table('destinations')->where('code', 'UK')->first();
        $caDestination = DB::table('destinations')->where('code', 'CA')->first();

        if ($ukDestination) {
            DB::table('zone')
                ->where('destination_id', $ukDestination->id)
                ->where('zone_category', 'zipcode')
                ->delete();
        }

        if ($caDestination) {
            DB::table('zone')
                ->where('destination_id', $caDestination->id)
                ->where('zone_category', 'zipcode')
                ->delete();
        }
    }
};
